before_install:
 - cd pkg

language: r

cache: packages

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

# Install nlopt package to help nloptr install
# glpk-utils and libglpk-dev are needed because of DHARMa #166
addons:
  apt:
    packages:
      - libnlopt-dev
      - libglpk-dev