! Soil Parameters ---------------------------

beta_fol    = pars_litter(1,:)
eta_11_fol  = pars_litter(2,:)
e0_fol    	= pars_litter(3,:)
fc_fol    	= pars_litter(4,:)
delay_fol   = pars_litter(5,:)
q0_fol      = pars_litter(6,:)
z_leaves 	= pars_litter(7,:)

beta_root   = pars_litter(8,:)
eta_11_root = pars_litter(9,:)
e0_root    	= pars_litter(10,:)
fc_root    	= pars_litter(11,:)
delay_root  = pars_litter(12,:)
q0_root    	= pars_litter(13,:)
z_root 		= pars_litter(14,:)

beta_bran   = pars_litter(15,:)
eta_11_bran = pars_litter(16,:)
e0_bran    	= pars_litter(17,:)
fc_bran    	= pars_litter(18,:)
delay_bran  = pars_litter(19,:)
q0_bran    	= pars_litter(20,:)
z_bran 		= pars_litter(21,:)

beta_stem   = pars_litter(22,:)
eta_11_stem = pars_litter(23,:)
e0_stem    	= pars_litter(24,:)
fc_stem    	= pars_litter(25,:)
delay_stem  = pars_litter(26,:)
q0_stem    	= pars_litter(27,:)
z_stem	 	= pars_litter(28,:)

beta_soc    = pars_soc(1)
eta_11_soc  = pars_soc(2)
e0_soc    	= pars_soc(3)
fc_soc    	= pars_soc(4)
delay_soc   = pars_soc(5)
q0_soc    	= pars_soc(6)
